# Generated by Django 4.2.7 on 2023-11-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='product_thumbnails/'),
        ),
    ]
