# Generated by Django 4.2.7 on 2023-11-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_thumbnail_product_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnails',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category'),
        ),
    ]
