# Generated by Django 4.2.7 on 2023-11-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_images/'),
        ),
    ]
